#!/usr/bin/env python3
"""
Splatline Video Splat Viewer — View all video frames as splats in the Splatline editor.

Takes the PLY files generated by run_video_3d.py and opens them in the
Splatline editor. Two modes:

  merge  — Combine all frame PLYs into one big splat scene (default)
  multi  — Load each frame as a separate splat in the editor

Usage:
  python run_video_splat.py [output_dir] [mode]

  python run_video_splat.py                          # uses default output_grok_3d
  python run_video_splat.py output_grok_3d merge     # merge all frames into one scene
  python run_video_splat.py output_grok_3d multi     # each frame is a separate splat
  python run_video_splat.py output_grok_3d merge 5   # merge, only frames 0-4
"""
import sys
import shutil
import http.server
import socketserver
import threading
import webbrowser
import time
import subprocess
from pathlib import Path

import numpy as np


def convert_to_standard_ply(input_path, output_path):
    """Convert SHARP PLY to standard 3DGS PLY (strip extra elements)."""
    from plyfile import PlyData, PlyElement

    ply = PlyData.read(str(input_path))

    if len(ply.elements) == 1:
        shutil.copy2(input_path, output_path)
        return

    vertex = ply['vertex']
    new_vertex = PlyElement.describe(vertex.data, 'vertex')
    new_ply = PlyData([new_vertex], text=False, byte_order='<')
    new_ply.write(str(output_path))


def merge_ply_files(ply_paths, output_path, max_per_frame=50000):
    """Merge multiple PLY files into a single combined PLY.

    Subsamples each frame to max_per_frame splats (kept by highest opacity)
    to keep the merged file manageable for the browser.
    """
    from plyfile import PlyData, PlyElement

    # First pass: figure out the vertex dtype from the first file
    first_ply = PlyData.read(str(ply_paths[0]))
    vertex = first_ply['vertex']
    dtype = vertex.data.dtype
    total_splats = 0

    # Open output file and write header
    with open(output_path, 'wb') as f:
        # Count total splats after subsampling
        frame_counts = []
        for ply_path in ply_paths:
            ply = PlyData.read(str(ply_path))
            count = min(ply['vertex'].count, max_per_frame)
            frame_counts.append(count)
            total_splats += count

        # Write PLY header
        header = f"ply\nformat binary_little_endian 1.0\nelement vertex {total_splats}\n"
        for name in dtype.names:
            t = dtype[name]
            if t.kind == 'f':
                header += f"property float {name}\n"
            elif t.kind == 'u':
                header += f"property uchar {name}\n"
            else:
                header += f"property {t} {name}\n"
        header += "end_header\n"
        f.write(header.encode('ascii'))

        # Second pass: subsample and write each frame
        for i, ply_path in enumerate(ply_paths):
            ply = PlyData.read(str(ply_path))
            vertex = ply['vertex']
            data = vertex.data

            # Subsample: keep top-opacity splats
            if vertex.count > max_per_frame:
                opacities = data['opacity']
                top_idx = np.argsort(opacities)[-max_per_frame:]
                data = data[top_idx]

            data = data.copy()
            # Offset each frame along Z so the sequence is visible in 3D
            data['z'] = data['z'] + float(i * 2.0)

            f.write(data.tobytes())
            print(f"  Frame {i}: {len(data):,} splats (z-offset={i*2.0:.1f})")

    size_mb = output_path.stat().st_size / 1e6
    print(f"  Merged: {total_splats:,} total splats, {size_mb:.1f} MB -> {output_path.name}")
    return output_path


def find_or_build_editor():
    """Find or build the Splatline editor dist files."""
    dist_dir = Path("/tmp/supersplat/dist")
    if (dist_dir / "index.html").exists() and (dist_dir / "index.js").exists():
        return dist_dir

    print("Cloning Splatline editor source...")
    repo_dir = Path("/tmp/supersplat")
    if not repo_dir.exists():
        subprocess.run(
            ["git", "clone", "--depth", "1", "https://github.com/playcanvas/supersplat.git", str(repo_dir)],
            capture_output=True, text=True, timeout=120
        )

    print("Installing dependencies...")
    subprocess.run(["npm", "install"], cwd=str(repo_dir),
                   capture_output=True, text=True, timeout=120)

    print("Building editor...")
    subprocess.run(["npm", "run", "build"], cwd=str(repo_dir),
                   capture_output=True, text=True, timeout=120)

    dist_dir = repo_dir / "dist"
    if (dist_dir / "index.html").exists():
        return dist_dir
    return None


def main():
    # Parse args
    output_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("output_grok_3d")
    mode = sys.argv[2] if len(sys.argv) > 2 else "merge"
    max_frames = int(sys.argv[3]) if len(sys.argv) > 3 else None

    gaussians_dir = output_dir / "gaussians"
    if not gaussians_dir.exists():
        print(f"Error: No gaussians directory found at {gaussians_dir}")
        print("Run run_video_3d.py first to generate the 3D PLY files.")
        sys.exit(1)

    ply_files = sorted(gaussians_dir.glob("*.ply"))
    if not ply_files:
        print(f"Error: No PLY files found in {gaussians_dir}")
        sys.exit(1)

    if max_frames:
        ply_files = ply_files[:max_frames]

    print("=" * 60)
    print("SPLATLINE VIDEO SPLAT VIEWER")
    print("=" * 60)
    print(f"Output dir: {output_dir}")
    print(f"PLY files:  {len(ply_files)}")
    print(f"Mode:       {mode}")
    print()

    # Find or build editor
    editor_dist = find_or_build_editor()
    if not editor_dist:
        print("Error: Could not build Splatline editor")
        sys.exit(1)

    # Fresh viewer directory
    viewer_dir = Path("/tmp/splatline_splat_viewer")
    if viewer_dir.exists():
        shutil.rmtree(viewer_dir)
    viewer_dir.mkdir(parents=True, exist_ok=True)

    print("Copying Splatline editor...")
    shutil.copytree(editor_dist, viewer_dir, dirs_exist_ok=True)

    # Disable service worker and rename title to Splatline
    index_html = (viewer_dir / "index.html").read_text()
    index_html = index_html.replace("navigator.serviceWorker", "null && navigator.serviceWorker")
    index_html = index_html.replace("<title>SuperSplat</title>", "<title>Splatline</title>")
    (viewer_dir / "index.html").write_text(index_html)

    # Build the URL for loading PLYs
    if mode == "merge":
        # Merge all frames into one PLY (subsampled to keep file size reasonable)
        # 50K splats/frame × 80 frames = 4M splats ≈ 270 MB — manageable for browser
        max_per_frame = 50000
        print(f"\nMerging {len(ply_files)} frames into one splat scene...")
        print(f"  (subsampling to {max_per_frame:,} splats per frame)")
        merged_path = viewer_dir / "merged.ply"
        merge_ply_files(ply_files, merged_path, max_per_frame=max_per_frame)
        load_url = "merged.ply"
        filename = f"{output_dir.name}_merged.ply"
    else:
        # Multi mode: convert each frame and load them all
        print(f"\nConverting {len(ply_files)} frames to standard PLY...")
        load_params = []
        for i, ply_path in enumerate(ply_files):
            std_path = viewer_dir / f"frame_{i:04d}.ply"
            convert_to_standard_ply(ply_path, std_path)
            load_params.append(f"load=frame_{i:04d}.ply&filename={ply_path.name}")
            print(f"  [{i+1}/{len(ply_files)}] {ply_path.name}")
        load_url = "&".join(load_params)
        filename = None

    # Web server
    class Handler(http.server.SimpleHTTPRequestHandler):
        def __init__(self, *args, **kwargs):
            super().__init__(*args, directory=str(viewer_dir), **kwargs)

        def end_headers(self):
            if self.path.endswith('.js'):
                self.send_header('Content-Type', 'text/javascript')
            elif self.path.endswith('.css'):
                self.send_header('Content-Type', 'text/css')
            elif self.path.endswith('.json'):
                self.send_header('Content-Type', 'application/json')
            elif self.path.endswith('.ply'):
                self.send_header('Content-Type', 'application/octet-stream')
            elif self.path.endswith('.wasm'):
                self.send_header('Content-Type', 'application/wasm')
            self.send_header('Cache-Control', 'no-store, no-cache, must-revalidate')
            super().end_headers()

        def log_message(self, format, *args):
            pass

    # Find available port
    server = None
    PORT = 8765
    for port in range(8765, 8780):
        try:
            socketserver.TCPServer.allow_reuse_address = True
            server = socketserver.ThreadingTCPServer(("localhost", port), Handler)
            PORT = port
            break
        except OSError:
            continue

    if server is None:
        print("Error: No available port (8765-8779 all in use)")
        sys.exit(1)

    print()
    print(f"Editor: http://localhost:{PORT}")
    print()
    if mode == "merge":
        print("All frames merged into one splat scene.")
        print("Each frame is offset 2 units along Z so you can see the sequence.")
    else:
        print(f"Each frame loaded as a separate splat ({len(ply_files)} splats).")
        print("Use the scene panel to toggle visibility per frame.")
    print()
    print("Controls:")
    print("  Left drag:    Orbit")
    print("  Right drag:   Pan")
    print("  Scroll:       Zoom")
    print("  F:            Frame scene")
    print("  Shift+click:  Select splats")
    print("  Drag .ply:    Load another file")
    print()
    print("Opening editor... (Ctrl+C to stop)")

    server_thread = threading.Thread(target=server.serve_forever, daemon=True)
    server_thread.start()

    time.sleep(1)

    if mode == "merge":
        url = f"http://localhost:{PORT}/index.html?load={load_url}&filename={filename}"
    else:
        url = f"http://localhost:{PORT}/index.html?{load_url}"

    webbrowser.open(url)

    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        print("\nShutting down...")
        server.shutdown()
        print("Done.")


if __name__ == "__main__":
    main()
